# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: IPTV
email: idi.aminx@gmail.com
description: # this means to ignore newlines until "baseurl:"
  IPTV iptv free channels,
  IPTV beIN sports channels, IPTV rusian match channels.
  Bein Sports are sports channels that send live
  sports events such football, basketball,
  handball, formula 1, tenis and moto gp among others.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://huawei-iptv.tk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  idiaminx

# Build settings
markdown: kramdown

license: CCO-by-3.0 Unported
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
