# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bein Sports
email: abuse.ombudsman@gmail.com
description: # this means to ignore newlines until "baseurl:"
  Bein Sports are sports channels that send live
  a lot of sports events such football, basketball,
  handball, formula 1, tenis and moto GP among others.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://abuseombudsman.github.io/iptv" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  abuseombudsman

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
